# Generated by Django 3.1.7 on 2021-02-27 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Family Name')),
                ('code', models.CharField(blank=True, max_length=6, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='FitnessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Bike', 'Bike'), ('Walk', 'Walk'), ('Run', 'Run'), ('Sports', 'Sports')], default='Bike', max_length=10)),
                ('calories', models.IntegerField(default=100)),
                ('duration', models.DurationField(default='00:30:00', help_text='HH:MM:ss format')),
            ],
        ),
    ]
