# Generated by Django 3.0.7 on 2020-08-12 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessrecord',
            name='calories',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='duration',
            field=models.DurationField(default='00:05:00', help_text='HH:MM:ss format'),
        ),
        migrations.CreateModel(
            name='UserLeaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.IntegerField(default=0)),
                ('total_duration', models.DurationField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
