# Generated by Django 3.0.7 on 2021-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210225_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Family Name'),
        ),
    ]
